# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    example.sample.boardservice:
        class: Example\SampleBundle\Services\BoardService
        arguments: ["@doctrine.orm.entity_manager"]
    example.sample.cardlistservice:
        class: Example\SampleBundle\Services\CardListService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.boardservice"]
    example.sample.cardservice:
        class: Example\SampleBundle\Services\CardService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.cardlistservice"]
    example.sample.taskservice:
        class: Example\SampleBundle\Services\TaskService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.cardservice"]
    example.sample.userservice:
        class: Example\SampleBundle\Services\UserService
        arguments: ["@doctrine.orm.entity_manager"]
    example.sample.likeservice:
        class: Example\SampleBundle\Services\LikeService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.boardservice", "@example.sample.userservice"]
    example.sample.commentservice:
        class: Example\SampleBundle\Services\CommentService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.cardservice" , "@example.sample.userservice"]
    example.sample.tagservice:
        class: Example\SampleBundle\Services\TagService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.boardservice", "@example.sample.cardservice"]
    example.sample.entryservice:
        class: Example\SampleBundle\Services\EntryService
        arguments: ["@doctrine.orm.entity_manager", "@example.sample.boardservice"]
