services:
  my_board_dao:
    class: Example\SampleBundle\DAO\BoardDAO
    arguments:
      entityManager: '@doctrine.orm.entity_manager'
  my_board_service:
    class: Example\SampleBundle\Services\BoardService
    arguments:
      boardDAO: '@my_board_dao'
  my_board_rest:
    class: Example\SampleBundle\Controller\DefaultController
    arguments:
      boardService: '@my_board_service'




